server:
  port: 8080
spring:
  freemarker:
    charset: UTF-8
    suffix: .html
    content-type: text/html
    enabled: true
    cache: false
    template-loader-path: classpath:/templates/
    request-context-attribute: req
logging:
  level:
    com.onedrivex: DEBUG